spring.application.name=spring-props-usages-in-conditionals

my.props.prop0=true
my.props.prop1=true
my.props.prop2=true
my.props.prop3=true
my.props.prop4=true
my.props.prop5=true
my.props.prop6=true
my.props.prop7=true
my.props.prop8=true
my.props.prop9=true
my.props.prop10=true
my.props.prop11=true
my.props.prop12=true
my.props.prop13=true
my.props.prop14=true
